#/usr/bin/bash

unset COLORFGBG COLORTERM COMMAND_MODE HOME ITERM_PROFILE ITERM_SESSION_ID LC_CTYPE LC_TERMINAL LC_TERMINAL_VERSION LOGNAME LaunchInstanceID MAIL OLDPWD PATH PWD SECURITYSESSIONID SHELL SHLVL SSH_AUTH_SOCK TERM TERM_PROGRAM TERM_PROGRAM_VERSION TERM_SESSION_ID TMPDIR USER XPC_FLAGS XPC_SERVICE_NAME _ __CF_USER_TEXT_ENCODING
